exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('users')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {
          password_hash:
            '$2a$10$DS.5tCCdESDCgLQp89OkHOoHw89i2qidMDytFpnnIRPQiSj8f6/N.',
          gender: 'male',
          first_name: 'Hossein',
          last_name: 'Heidari',
          photo: '../uploads/users/1122_user.JPG',
          height: 180,
          username: 'hossein',
          bio: 'A passionate freestylist.',
          created_at: '2020-05-19 10:00:40',
          updated_at: null,
          updated_by: null,
          sports: ['Basketball'],
          photos: [
            '../uploads/users/1122_user_pic_1',
            '../uploads/users/1122_user_pic_2',
          ],
          friends: [],
          scopes: ['edit_sbs_scopes', 'edit_locations', 'edit_events'],
          verified: true,
        },
        // {
        //   id: 1133,
        //   gender: 'female',
        //   first_name: 'Parnia',
        //   last_name: 'Esna Ashari',
        //   photo: '1122_user.JPG',
        //   height: 175,
        //   username: 'parnia',
        //   bio: 'Only God can get passed me.',
        //   created_at: '1598032502815',
        //   updated_at: '',
        //   sport: 'Basketball',
        //   photos: [''],
        //   friends: [1122, 1144, 1155, 1166],
        //   scopes: ['c', 'a', 'b'],
        //   verified: true,
        // },
        // {
        //   id: 1144,
        //   gender: 'male',
        //   first_name: 'Mehran',
        //   last_name: 'Shabani',
        //   photo: '1122_user.JPG',
        //   height: 190,
        //   username: 'mehran',
        //   bio: "Don't waste my time playing nonsense.",
        //   created_at: '1598032502915',
        //   updated_at: '',
        //   sport: 'Basketball',
        //   photos: ['1122_user_pic_1', '1122_user_pic_2'],
        //   friends: [1122, 1133, 1155, 1166],
        //   scopes: ['c', 'a', 'b'],
        //   verified: true,
        // },
        // {
        //   id: 1177,
        //   gender: 'male',
        //   first_name: 'Mammad',
        //   last_name: 'Sobhani',
        //   photo: '1122_user.JPG',
        //   height: 183,
        //   username: 'mammad',
        //   bio: 'Not tryina prove no nothing to nobody.',
        //   created_at: '1598032503715',
        //   updated_at: '',
        //   sport: 'Basketball',
        //   photos: ['1122_user_pic_1', '1122_user_pic_2'],
        //   friends: [1122, 1133, 1155, 1166],
        //   scopes: ['c', 'a', 'b'],
        //   verified: '',
        // },
        // {
        //   id: 1188,
        //   gender: 'female',
        //   first_name: 'Masoome',
        //   last_name: 'Esmaili',
        //   photo: '1122_user.JPG',
        //   height: 180,
        //   username: 'massoome',
        //   bio: "I'll chase you down if you bullshit.",
        //   created_at: '1598032502819',
        //   updated_at: '',
        //   sport: 'Basketball',
        //   photos: ['1122_user_pic_1', '1122_user_pic_2'],
        //   friends: [1122, 1133, 1155, 1166],
        //   scopes: ['c', 'a', 'b'],
        //   verified: true,
        // },
      ])
    })
}
